//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "ChangePicView.xaml.h"

void ::Lab3::ChangePicView::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///ChangePicView.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Lab3::ChangePicView::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->NewPicText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 2:
            {
                this->OldPicText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 3:
            {
                this->NewPic = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->NewPic))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Lab3::ChangePicView::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&ChangePicView::NewPic_Click);
            }
            break;
        case 4:
            {
                this->OldPic = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->OldPic))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Lab3::ChangePicView::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&ChangePicView::OldPic_Click);
            }
            break;
        case 5:
            {
                this->Back = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Back))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Lab3::ChangePicView::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&ChangePicView::Back_Click);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Lab3::ChangePicView::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


