#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class TextBox;
                ref class Button;
            }
        }
    }
}

namespace Lab3
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class RoomView1 : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock;
        private: ::Windows::UI::Xaml::Controls::TextBox^ RoomTitle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ RoomDescription;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Latitude;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock7;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Longitude;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ RoomVolume;
        private: ::Windows::UI::Xaml::Controls::Button^ SaveButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ em;
        private: ::Windows::UI::Xaml::Controls::Button^ HomeButton;
        private: ::Windows::UI::Xaml::Controls::Button^ Wall4;
        private: ::Windows::UI::Xaml::Controls::Button^ Ceiling;
        private: ::Windows::UI::Xaml::Controls::Button^ Floor;
        private: ::Windows::UI::Xaml::Controls::Button^ Wall1;
        private: ::Windows::UI::Xaml::Controls::Button^ Wall2;
        private: ::Windows::UI::Xaml::Controls::Button^ Wall3;
    };
}

