//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "WallView1.xaml.h"

void ::Lab3::WallView1::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///WallView1.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Lab3::WallView1::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->textBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 2:
            {
                this->Title = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 3:
            {
                this->textBlock2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 4:
            {
                this->Description = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 5:
            {
                this->textBlock4 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 6:
            {
                this->Area = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 7:
            {
                this->textBlock6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 8:
            {
                this->ChangePicture = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ChangePicture))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Lab3::WallView1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WallView1::ChangePicture_Click);
            }
            break;
        case 9:
            {
                this->WallImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 10:
            {
                this->Save = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Save))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Lab3::WallView1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WallView1::Save_Click);
            }
            break;
        case 11:
            {
                this->Back = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Back))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Lab3::WallView1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WallView1::Back_Click);
            }
            break;
        case 12:
            {
                this->Home = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Home))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Lab3::WallView1::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WallView1::Home_Click);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Lab3::WallView1::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


